// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhEGPZnW955pFDWZAATPrGuSMuX7RgTec',
    appId: '1:709575599202:web:5eef672fefa85ddd61dd3b',
    messagingSenderId: '709575599202',
    projectId: 'stitch-dda0b',
    authDomain: 'stitch-dda0b.firebaseapp.com',
    storageBucket: 'stitch-dda0b.appspot.com',
    measurementId: 'G-6R2P6VN5T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlePwHkVbzQiiSOl3afIWZaeq60oH2Juo',
    appId: '1:709575599202:android:539e6e23027420ae61dd3b',
    messagingSenderId: '709575599202',
    projectId: 'stitch-dda0b',
    storageBucket: 'stitch-dda0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR97fXpf2Erd8jpwVCdjAgcP_XxOkIF00',
    appId: '1:709575599202:ios:5dee3a38ac7d41fa61dd3b',
    messagingSenderId: '709575599202',
    projectId: 'stitch-dda0b',
    storageBucket: 'stitch-dda0b.appspot.com',
    androidClientId: '709575599202-nsmg8413h746m9jrsfm03ub1oc6to0kq.apps.googleusercontent.com',
    iosClientId: '709575599202-dq4fojd7t2ib0oiicomc67nliarb0bu9.apps.googleusercontent.com',
    iosBundleId: 'com.obeckley.stitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR97fXpf2Erd8jpwVCdjAgcP_XxOkIF00',
    appId: '1:709575599202:ios:955c8e9d963965d061dd3b',
    messagingSenderId: '709575599202',
    projectId: 'stitch-dda0b',
    storageBucket: 'stitch-dda0b.appspot.com',
    androidClientId: '709575599202-nsmg8413h746m9jrsfm03ub1oc6to0kq.apps.googleusercontent.com',
    iosClientId: '709575599202-0vmtk7mn91o8glf1dksp65mbr7sqiei2.apps.googleusercontent.com',
    iosBundleId: 'com.example.stitch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhEGPZnW955pFDWZAATPrGuSMuX7RgTec',
    appId: '1:709575599202:web:baac157289963a7a61dd3b',
    messagingSenderId: '709575599202',
    projectId: 'stitch-dda0b',
    authDomain: 'stitch-dda0b.firebaseapp.com',
    storageBucket: 'stitch-dda0b.appspot.com',
    measurementId: 'G-L9QRHD8390',
  );
}
